### ISSUE TITLE
Liquidity Premium

### ISSUE THREAD

**Issue by miguelmtzinf** [aave/aave-v4#11]
Implementation of liquidity premiums, where borrowers are over-charged based on the risk of their collateral.

- ETH as collateral is risk free, so 0 additional charge.
- each position has an average premium calculated as the weighted average of all collaterals
- each asset has an assigned risk factor that ranges from 0 to 1.
- borrow rate must be = base borrow rate + base borrow rate * avgRiskPremium
- avgRiskPremium is calculated using the value of collateral in base currency terms
- on supply side, an avg risk premium of all positions is maintained so supply rate must be = borrow rate * avg premium * utilization rate

Note that we must keep LiquidityHub and BorrowModule separate (decoupled).

**Comment by CanonicalJP** [comment]
Task was carried out in https://github.com/aave/aave-v4/issues/40 and https://github.com/aave/aave-v4/issues/41
