### ISSUE TITLE
Rebalance risk premium of user

### ISSUE THREAD

**Issue by miguelmtzinf** [aave/aave-v4#20]
The risk premium of a user depends on collateral composition, which depends on the amount of assets supplied as collateral (impacted by yield),  asset prices and reserve liquidity premium changes. This is variable, but we are following a static computation approach, where we are recomputing every time a user performs an action.

In case the user does not interact with the protocol, the risk premium remains constant except:
    - If risk premium of the user lowers (better collateral asset quality) → the user can refresh by recomputing the risk premium.
    - If risk premium of the user increases (lower quality) → only governance (or special entity) can refresh.

**Comment by CanonicalJP** [comment]
Work was done in https://github.com/aave/aave-v4/issues/40 and https://github.com/aave/aave-v4/issues/41
