### ISSUE TITLE
Calculation of user HF and risk premium

### ISSUE THREAD

**Issue by miguelmtzinf** [aave/aave-v4#35]
Add a user-facing function to set an asset as collateral.
- The user must have supplied the asset already

Create `getter` to compute HF of the user by iterating through user's position

Create `getter` to compute risk premium of the user
- weight = Amount of collateral * Price of the asset
- value = Liquidity premium of the asset

**Comment by yan-man** [comment]
getter to compute risk premium of the user
- depends on the LP parameter in spoke, blocked by https://github.com/aave/aave-v4/issues/40

**Comment by yan-man** [comment]
> Add a user-facing function to set an asset as collateral.

Also covered in https://github.com/aave/aave-v4/issues/25
